"""
models/backtest.py
Engine backtest sederhana untuk evaluasi performa model.
"""
import numpy as np
import pandas as pd
from loguru import logger


class Backtester:
    """Simulasi trading berbasis sinyal ML."""

    def __init__(self, config: dict):
        self.risk_cfg = config["risk"]
        backtest_cfg = config.get("backtest", {})
        self.initial_balance = backtest_cfg.get("initial_balance", 10_000.0)
        self.leverage = backtest_cfg.get("leverage", 1)
        self.pip_value = backtest_cfg.get("pip_value", 10.0)
        self.commission = backtest_cfg.get("commission_per_trade", 0.0)
        self.point = config["data"].get("point", 0.00001)
        self.use_leverage_for_lot_sizing = backtest_cfg.get("use_leverage_for_lot_sizing", False)
        self.margin_requirement = 1.0 / self.leverage if self.leverage > 0 else 1.0
        # store last trades generated by run()
        self.last_trades = []

    def run(self, df: pd.DataFrame, signals: list, verbose: bool = True) -> dict:
        """
        Jalankan backtest.

        Args:
            df: DataFrame dengan kolom [open, high, low, close, atr]
            signals: list string "BUY"/"SELL"/"HOLD" sepanjang df

        Returns:
            dict metrik performa
        """
        assert len(df) == len(signals), "Panjang df dan signals harus sama."

        balance    = self.initial_balance
        equity_curve = [balance]
        trades     = []
        open_trade = None

        sl_mult = self.risk_cfg["sl_atr_multiplier"]
        tp_mult = self.risk_cfg["tp_atr_multiplier"]

        for i, (idx, row) in enumerate(df.iterrows()):
            signal = signals[i]
            price  = row["close"]
            atr    = row.get("atr", price * 0.001)

            # Cek apakah open trade kena SL/TP
            if open_trade:
                hit, pnl = self._check_exit(open_trade, row)
                if hit:
                    balance += pnl
                    open_trade["exit_price"] = price
                    open_trade["exit_time"]  = idx
                    open_trade["pnl"]        = pnl
                    open_trade["result"]     = "WIN" if pnl > 0 else "LOSS"
                    trades.append(open_trade)
                    open_trade = None

            # Buka trade baru (satu trade di satu waktu)
            if open_trade is None and signal in ("BUY", "SELL"):
                sl_dist = atr * sl_mult
                tp_dist = atr * tp_mult
                lot_size = self._calc_lot(balance, sl_dist, price)

                if signal == "BUY":
                    sl = price - sl_dist
                    tp = price + tp_dist
                else:
                    sl = price + sl_dist
                    tp = price - tp_dist

                open_trade = {
                    "direction": signal,
                    "entry_price": price,
                    "entry_time": idx,
                    "sl": sl,
                    "tp": tp,
                    "lot": lot_size,
                    "risk_amount": balance * self.risk_cfg["max_risk_per_trade"],
                }

            equity_curve.append(balance)

        # Tutup trade yang masih terbuka di akhir
        if open_trade:
            last_row = df.iloc[-1]
            pnl = self._calc_pnl(open_trade, last_row["close"])
            balance += pnl
            open_trade["exit_price"] = last_row["close"]
            open_trade["exit_time"]  = df.index[-1]
            open_trade["pnl"]        = pnl
            open_trade["result"]     = "WIN" if pnl > 0 else "LOSS"
            trades.append(open_trade)

        equity_curve.append(balance)
        metrics = self._calculate_metrics(trades, equity_curve, df)

        # persist last trades for external inspection
        self.last_trades = trades

        if verbose:
            self._print_summary(metrics)

        return metrics

    def _check_exit(self, trade: dict, row: pd.Series) -> tuple:
        """Cek apakah SL atau TP tercapai dalam candle ini."""
        if trade["direction"] == "BUY":
            if row["low"] <= trade["sl"]:
                return True, self._calc_pnl(trade, trade["sl"])
            if row["high"] >= trade["tp"]:
                return True, self._calc_pnl(trade, trade["tp"])
        else:  # SELL
            if row["high"] >= trade["sl"]:
                return True, self._calc_pnl(trade, trade["sl"])
            if row["low"] <= trade["tp"]:
                return True, self._calc_pnl(trade, trade["tp"])
        return False, 0.0

    def _calc_pnl(self, trade: dict, exit_price: float) -> float:
        """Hitung PnL dalam USD (asumsi pip value dan point diambil dari config)."""
        pips = (exit_price - trade["entry_price"]) / self.point / 10.0
        if trade["direction"] == "SELL":
            pips = -pips
        gross_pnl = pips * self.pip_value * trade["lot"]
        return gross_pnl - self.commission

    def _calc_lot(self, balance: float, sl_dist: float, price: float) -> float:
        risk_amount = balance * self.risk_cfg["max_risk_per_trade"]
        sl_pips = sl_dist / self.point / 10.0
        if sl_pips <= 0:
            return 0.01

        raw_lot = risk_amount / (sl_pips * self.pip_value)
        if self.use_leverage_for_lot_sizing and self.leverage > 1:
            available_margin = balance * self.leverage
            margin_needed_per_lot = 100_000 * price * self.margin_requirement
            max_lot_by_margin = available_margin / margin_needed_per_lot if margin_needed_per_lot > 0 else 100.0
            raw_lot = min(raw_lot, max_lot_by_margin)

        return max(0.01, min(round(raw_lot, 2), 10.0))

    def _calculate_metrics(self, trades: list, equity: list, df: pd.DataFrame) -> dict:
        if not trades:
            return {
                "total_trades": 0,
                "win_trades": 0,
                "loss_trades": 0,
                "win_rate": 0,
                "profit_factor": 0,
                "sharpe_ratio": 0,
                "max_drawdown": 0,
                "total_pnl": 0,
                "avg_win": 0,
                "avg_loss": 0,
                "expectancy": 0,
                "final_balance": self.initial_balance,
                "return_pct": 0,
            }

        pnls = [t["pnl"] for t in trades]
        wins = [p for p in pnls if p > 0]
        losses = [p for p in pnls if p <= 0]
        total_pnl = sum(pnls)
        win_rate  = len(wins) / len(pnls) if pnls else 0
        gross_profit = sum(wins)
        gross_loss   = abs(sum(losses))
        profit_factor = gross_profit / gross_loss if gross_loss > 0 else float("inf")

        # Equity curve metrics
        eq_arr = np.array(equity)
        returns = np.diff(eq_arr) / eq_arr[:-1]
        sharpe = (returns.mean() / (returns.std() + 1e-10)) * np.sqrt(252 * 24)

        # Max drawdown
        peak = np.maximum.accumulate(eq_arr)
        dd   = (eq_arr - peak) / (peak + 1e-10)
        max_dd = float(dd.min())

        # Avg win/loss
        avg_win  = np.mean(wins)  if wins   else 0
        avg_loss = np.mean(losses) if losses else 0
        expectancy = win_rate * avg_win + (1 - win_rate) * avg_loss

        return {
            "total_trades":   len(trades),
            "win_trades":     len(wins),
            "loss_trades":    len(losses),
            "win_rate":       round(win_rate, 4),
            "profit_factor":  round(profit_factor, 4),
            "sharpe_ratio":   round(float(sharpe), 4),
            "max_drawdown":   round(max_dd, 4),
            "total_pnl":      round(total_pnl, 2),
            "avg_win":        round(avg_win, 2),
            "avg_loss":       round(avg_loss, 2),
            "expectancy":     round(expectancy, 2),
            "final_balance":  round(self.initial_balance + total_pnl, 2),
            "return_pct":     round(total_pnl / self.initial_balance * 100, 2),
        }

    def _print_summary(self, m: dict):
        logger.info("\n📊 Backtest Results:")
        logger.info(f"  Total Trades  : {m['total_trades']} (W:{m['win_trades']} L:{m['loss_trades']})")
        logger.info(f"  Win Rate      : {m['win_rate']*100:.1f}%")
        logger.info(f"  Profit Factor : {m['profit_factor']:.2f}")
        logger.info(f"  Sharpe Ratio  : {m['sharpe_ratio']:.2f}")
        logger.info(f"  Max Drawdown  : {m['max_drawdown']*100:.1f}%")
        logger.info(f"  Total PnL     : ${m['total_pnl']:.2f} ({m['return_pct']:.1f}%)")
        logger.info(f"  Final Balance : ${m['final_balance']:.2f}")
        logger.info(f"  Expectancy    : ${m['expectancy']:.2f}/trade")
